export const recommendation_1 = [
  {
    id: 2,
    label: "Avengers: Endgame",
    wide: "http://localhost:3000/wide/wide2.webp",
    poster: "http://localhost:3000/poster/poster2.webp",
    focus: "http://localhost:3000/focus/focus2.webp",
    title: "http://localhost:3000/title/title2.webp",
  },
  {
    id: 3,
    label: "Avengers: Infinity War",
    wide: "http://localhost:3000/wide/wide3.webp",
    poster: "http://localhost:3000/poster/poster3.webp",
    focus: "http://localhost:3000/focus/focus3.webp",
    title: "http://localhost:3000/title/title3.webp",
  },
  {
    id: 4,
    label: "Venom",
    wide: "http://localhost:3000/wide/wide4.webp",
    poster: "http://localhost:3000/poster/poster4.webp",
    focus: "http://localhost:3000/focus/focus4.webp",
    title: "http://localhost:3000/title/title4.webp",
  },
  {
    id: 5,
    label: "Transformers: The Last Knight",
    wide: "http://localhost:3000/wide/wide5.webp",
    poster: "http://localhost:3000/poster/poster5.webp",
    focus: "http://localhost:3000/focus/focus5.webp",
    title: "http://localhost:3000/title/title5.webp",
  },
  {
    id: 6,
    label: "Warcraft: The Beginning",
    wide: "http://localhost:3000/wide/wide6.webp",
    poster: "http://localhost:3000/poster/poster6.webp",
    focus: "http://localhost:3000/focus/focus6.webp",
    title: "http://localhost:3000/title/title6.webp",
  },
];

export const recommendation_2 = [
  {
    id: 3,
    label: "Avengers: Infinity War",
    wide: "http://localhost:3000/wide/wide3.webp",
    poster: "http://localhost:3000/poster/poster3.webp",
    focus: "http://localhost:3000/focus/focus3.webp",
    title: "http://localhost:3000/title/title3.webp",
  },
  {
    id: 4,
    label: "Venom",
    wide: "http://localhost:3000/wide/wide4.webp",
    poster: "http://localhost:3000/poster/poster4.webp",
    focus: "http://localhost:3000/focus/focus4.webp",
    title: "http://localhost:3000/title/title4.webp",
  },
  {
    id: 5,
    label: "Transformers: The Last Knight",
    wide: "http://localhost:3000/wide/wide5.webp",
    poster: "http://localhost:3000/poster/poster5.webp",
    focus: "http://localhost:3000/focus/focus5.webp",
    title: "http://localhost:3000/title/title5.webp",
  },
  {
    id: 6,
    label: "Warcraft: The Beginning",
    wide: "http://localhost:3000/wide/wide6.webp",
    poster: "http://localhost:3000/poster/poster6.webp",
    focus: "http://localhost:3000/focus/focus6.webp",
    title: "http://localhost:3000/title/title6.webp",
  },
  {
    id: 7,
    label: "Kong: Skull Island",
    wide: "http://localhost:3000/wide/wide7.webp",
    poster: "http://localhost:3000/poster/poster7.webp",
    focus: "http://localhost:3000/focus/focus7.webp",
    title: "http://localhost:3000/title/title7.webp",
  },
];

export const recommendation_3 = [
  {
    id: 4,
    label: "Venom",
    wide: "http://localhost:3000/wide/wide4.webp",
    poster: "http://localhost:3000/poster/poster4.webp",
    focus: "http://localhost:3000/focus/focus4.webp",
    title: "http://localhost:3000/title/title4.webp",
  },
  {
    id: 5,
    label: "Transformers: The Last Knight",
    wide: "http://localhost:3000/wide/wide5.webp",
    poster: "http://localhost:3000/poster/poster5.webp",
    focus: "http://localhost:3000/focus/focus5.webp",
    title: "http://localhost:3000/title/title5.webp",
  },
  {
    id: 6,
    label: "Warcraft: The Beginning",
    wide: "http://localhost:3000/wide/wide6.webp",
    poster: "http://localhost:3000/poster/poster6.webp",
    focus: "http://localhost:3000/focus/focus6.webp",
    title: "http://localhost:3000/title/title6.webp",
  },
  {
    id: 7,
    label: "Kong: Skull Island",
    wide: "http://localhost:3000/wide/wide7.webp",
    poster: "http://localhost:3000/poster/poster7.webp",
    focus: "http://localhost:3000/focus/focus7.webp",
    title: "http://localhost:3000/title/title7.webp",
  },
  {
    id: 8,
    label: "Divergent",
    wide: "http://localhost:3000/wide/wide8.webp",
    poster: "http://localhost:3000/poster/poster8.webp",
    focus: "http://localhost:3000/focus/focus8.webp",
    title: "http://localhost:3000/title/title8.webp",
  },
];

export const recommendation_4 = [
  {
    id: 5,
    label: "Transformers: The Last Knight",
    wide: "http://localhost:3000/wide/wide5.webp",
    poster: "http://localhost:3000/poster/poster5.webp",
    focus: "http://localhost:3000/focus/focus5.webp",
    title: "http://localhost:3000/title/title5.webp",
  },
  {
    id: 6,
    label: "Warcraft: The Beginning",
    wide: "http://localhost:3000/wide/wide6.webp",
    poster: "http://localhost:3000/poster/poster6.webp",
    focus: "http://localhost:3000/focus/focus6.webp",
    title: "http://localhost:3000/title/title6.webp",
  },
  {
    id: 7,
    label: "Kong: Skull Island",
    wide: "http://localhost:3000/wide/wide7.webp",
    poster: "http://localhost:3000/poster/poster7.webp",
    focus: "http://localhost:3000/focus/focus7.webp",
    title: "http://localhost:3000/title/title7.webp",
  },
  {
    id: 8,
    label: "Divergent",
    wide: "http://localhost:3000/wide/wide8.webp",
    poster: "http://localhost:3000/poster/poster8.webp",
    focus: "http://localhost:3000/focus/focus8.webp",
    title: "http://localhost:3000/title/title8.webp",
  },
  {
    id: 9,
    label: "Captain America: The Winter Soldier",
    wide: "http://localhost:3000/wide/wide9.webp",
    poster: "http://localhost:3000/poster/poster9.webp",
    focus: "http://localhost:3000/focus/focus9.webp",
    title: "http://localhost:3000/title/title9.webp",
  },
];
export const recommendation_5 = [
  {
    id: 6,
    label: "Warcraft: The Beginning",
    wide: "http://localhost:3000/wide/wide6.webp",
    poster: "http://localhost:3000/poster/poster6.webp",
    focus: "http://localhost:3000/focus/focus6.webp",
    title: "http://localhost:3000/title/title6.webp",
  },
  {
    id: 7,
    label: "Kong: Skull Island",
    wide: "http://localhost:3000/wide/wide7.webp",
    poster: "http://localhost:3000/poster/poster7.webp",
    focus: "http://localhost:3000/focus/focus7.webp",
    title: "http://localhost:3000/title/title7.webp",
  },
  {
    id: 8,
    label: "Divergent",
    wide: "http://localhost:3000/wide/wide8.webp",
    poster: "http://localhost:3000/poster/poster8.webp",
    focus: "http://localhost:3000/focus/focus8.webp",
    title: "http://localhost:3000/title/title8.webp",
  },
  {
    id: 9,
    label: "Captain America: The Winter Soldier",
    wide: "http://localhost:3000/wide/wide9.webp",
    poster: "http://localhost:3000/poster/poster9.webp",
    focus: "http://localhost:3000/focus/focus9.webp",
    title: "http://localhost:3000/title/title9.webp",
  },
  {
    id: 10,
    label: "Avengers",
    wide: "http://localhost:3000/wide/wide10.webp",
    poster: "http://localhost:3000/poster/poster10.webp",
    focus: "http://localhost:3000/focus/focus10.webp",
    title: "http://localhost:3000/title/title10.webp",
  },
];
export const recommendation_6 = [
  {
    id: 7,
    label: "Kong: Skull Island",
    wide: "http://localhost:3000/wide/wide7.webp",
    poster: "http://localhost:3000/poster/poster7.webp",
    focus: "http://localhost:3000/focus/focus7.webp",
    title: "http://localhost:3000/title/title7.webp",
  },
  {
    id: 8,
    label: "Divergent",
    wide: "http://localhost:3000/wide/wide8.webp",
    poster: "http://localhost:3000/poster/poster8.webp",
    focus: "http://localhost:3000/focus/focus8.webp",
    title: "http://localhost:3000/title/title8.webp",
  },
  {
    id: 9,
    label: "Captain America: The Winter Soldier",
    wide: "http://localhost:3000/wide/wide9.webp",
    poster: "http://localhost:3000/poster/poster9.webp",
    focus: "http://localhost:3000/focus/focus9.webp",
    title: "http://localhost:3000/title/title9.webp",
  },
  {
    id: 10,
    label: "Avengers",
    wide: "http://localhost:3000/wide/wide10.webp",
    poster: "http://localhost:3000/poster/poster10.webp",
    focus: "http://localhost:3000/focus/focus10.webp",
    title: "http://localhost:3000/title/title10.webp",
  },
  {
    id: 11,
    label: "Assassin's Creed",
    wide: "http://localhost:3000/wide/wide11.webp",
    poster: "http://localhost:3000/poster/poster11.webp",
    focus: "http://localhost:3000/focus/focus11.webp",
    title: "http://localhost:3000/title/title11.webp",
  },
];
export const recommendation_7 = [
  {
    id: 8,
    label: "Divergent",
    wide: "http://localhost:3000/wide/wide8.webp",
    poster: "http://localhost:3000/poster/poster8.webp",
    focus: "http://localhost:3000/focus/focus8.webp",
    title: "http://localhost:3000/title/title8.webp",
  },
  {
    id: 9,
    label: "Captain America: The Winter Soldier",
    wide: "http://localhost:3000/wide/wide9.webp",
    poster: "http://localhost:3000/poster/poster9.webp",
    focus: "http://localhost:3000/focus/focus9.webp",
    title: "http://localhost:3000/title/title9.webp",
  },
  {
    id: 10,
    label: "Avengers",
    wide: "http://localhost:3000/wide/wide10.webp",
    poster: "http://localhost:3000/poster/poster10.webp",
    focus: "http://localhost:3000/focus/focus10.webp",
    title: "http://localhost:3000/title/title10.webp",
  },
  {
    id: 11,
    label: "Assassin's Creed",
    wide: "http://localhost:3000/wide/wide11.webp",
    poster: "http://localhost:3000/poster/poster11.webp",
    focus: "http://localhost:3000/focus/focus11.webp",
    title: "http://localhost:3000/title/title11.webp",
  },
  {
    id: 12,
    label: "Avengers: Age Of Ultron",
    wide: "http://localhost:3000/wide/wide12.webp",
    poster: "http://localhost:3000/poster/poster12.webp",
    focus: "http://localhost:3000/focus/focus12.webp",
    title: "http://localhost:3000/title/title12.webp",
  },
];
export const recommendation_8 = [
  {
    id: 9,
    label: "Captain America: The Winter Soldier",
    wide: "http://localhost:3000/wide/wide9.webp",
    poster: "http://localhost:3000/poster/poster9.webp",
    focus: "http://localhost:3000/focus/focus9.webp",
    title: "http://localhost:3000/title/title9.webp",
  },
  {
    id: 10,
    label: "Avengers",
    wide: "http://localhost:3000/wide/wide10.webp",
    poster: "http://localhost:3000/poster/poster10.webp",
    focus: "http://localhost:3000/focus/focus10.webp",
    title: "http://localhost:3000/title/title10.webp",
  },
  {
    id: 11,
    label: "Assassin's Creed",
    wide: "http://localhost:3000/wide/wide11.webp",
    poster: "http://localhost:3000/poster/poster11.webp",
    focus: "http://localhost:3000/focus/focus11.webp",
    title: "http://localhost:3000/title/title11.webp",
  },
  {
    id: 12,
    label: "Avengers: Age Of Ultron",
    wide: "http://localhost:3000/wide/wide12.webp",
    poster: "http://localhost:3000/poster/poster12.webp",
    focus: "http://localhost:3000/focus/focus12.webp",
    title: "http://localhost:3000/title/title12.webp",
  },
  {
    id: 13,
    label: "Iron Man 3",
    wide: "http://localhost:3000/wide/wide13.webp",
    poster: "http://localhost:3000/poster/poster13.webp",
    focus: "http://localhost:3000/focus/focus13.webp",
    title: "http://localhost:3000/title/title13.webp",
  },
];
export const recommendation_9 = [
  {
    id: 10,
    label: "Avengers",
    wide: "http://localhost:3000/wide/wide10.webp",
    poster: "http://localhost:3000/poster/poster10.webp",
    focus: "http://localhost:3000/focus/focus10.webp",
    title: "http://localhost:3000/title/title10.webp",
  },
  {
    id: 11,
    label: "Assassin's Creed",
    wide: "http://localhost:3000/wide/wide11.webp",
    poster: "http://localhost:3000/poster/poster11.webp",
    focus: "http://localhost:3000/focus/focus11.webp",
    title: "http://localhost:3000/title/title11.webp",
  },
  {
    id: 12,
    label: "Avengers: Age Of Ultron",
    wide: "http://localhost:3000/wide/wide12.webp",
    poster: "http://localhost:3000/poster/poster12.webp",
    focus: "http://localhost:3000/focus/focus12.webp",
    title: "http://localhost:3000/title/title12.webp",
  },
  {
    id: 13,
    label: "Iron Man 3",
    wide: "http://localhost:3000/wide/wide13.webp",
    poster: "http://localhost:3000/poster/poster13.webp",
    focus: "http://localhost:3000/focus/focus13.webp",
    title: "http://localhost:3000/title/title13.webp",
  },
  {
    id: 14,
    label: "Kung Fu Panda 3",
    wide: "http://localhost:3000/wide/wide14.webp",
    poster: "http://localhost:3000/poster/poster14.webp",
    focus: "http://localhost:3000/focus/focus14.webp",
    title: "http://localhost:3000/title/title14.webp",
  },
];
export const recommendation_10 = [
  {
    id: 11,
    label: "Assassin's Creed",
    wide: "http://localhost:3000/wide/wide11.webp",
    poster: "http://localhost:3000/poster/poster11.webp",
    focus: "http://localhost:3000/focus/focus11.webp",
    title: "http://localhost:3000/title/title11.webp",
  },
  {
    id: 12,
    label: "Avengers: Age Of Ultron",
    wide: "http://localhost:3000/wide/wide12.webp",
    poster: "http://localhost:3000/poster/poster12.webp",
    focus: "http://localhost:3000/focus/focus12.webp",
    title: "http://localhost:3000/title/title12.webp",
  },
  {
    id: 13,
    label: "Iron Man 3",
    wide: "http://localhost:3000/wide/wide13.webp",
    poster: "http://localhost:3000/poster/poster13.webp",
    focus: "http://localhost:3000/focus/focus13.webp",
    title: "http://localhost:3000/title/title13.webp",
  },
  {
    id: 14,
    label: "Kung Fu Panda 3",
    wide: "http://localhost:3000/wide/wide14.webp",
    poster: "http://localhost:3000/poster/poster14.webp",
    focus: "http://localhost:3000/focus/focus14.webp",
    title: "http://localhost:3000/title/title14.webp",
  },
  {
    id: 15,
    label: "Dracula Untold",
    wide: "http://localhost:3000/wide/wide15.webp",
    poster: "http://localhost:3000/poster/poster15.webp",
    focus: "http://localhost:3000/focus/focus15.webp",
    title: "http://localhost:3000/title/title15.webp",
  },
];
export const recommendation_11 = [
  {
    id: 12,
    label: "Avengers: Age Of Ultron",
    wide: "http://localhost:3000/wide/wide12.webp",
    poster: "http://localhost:3000/poster/poster12.webp",
    focus: "http://localhost:3000/focus/focus12.webp",
    title: "http://localhost:3000/title/title12.webp",
  },
  {
    id: 13,
    label: "Iron Man 3",
    wide: "http://localhost:3000/wide/wide13.webp",
    poster: "http://localhost:3000/poster/poster13.webp",
    focus: "http://localhost:3000/focus/focus13.webp",
    title: "http://localhost:3000/title/title13.webp",
  },
  {
    id: 14,
    label: "Kung Fu Panda 3",
    wide: "http://localhost:3000/wide/wide14.webp",
    poster: "http://localhost:3000/poster/poster14.webp",
    focus: "http://localhost:3000/focus/focus14.webp",
    title: "http://localhost:3000/title/title14.webp",
  },
  {
    id: 15,
    label: "Dracula Untold",
    wide: "http://localhost:3000/wide/wide15.webp",
    poster: "http://localhost:3000/poster/poster15.webp",
    focus: "http://localhost:3000/focus/focus15.webp",
    title: "http://localhost:3000/title/title15.webp",
  },
  {
    id: 16,
    label: "Avatar: The Way of Water",
    wide: "http://localhost:3000/wide/wide16.webp",
    poster: "http://localhost:3000/poster/poster16.webp",
    focus: "http://localhost:3000/focus/focus16.webp",
    title: "http://localhost:3000/title/title16.webp",
  },
];
export const recommendation_12 = [
  {
    id: 13,
    label: "Iron Man 3",
    wide: "http://localhost:3000/wide/wide13.webp",
    poster: "http://localhost:3000/poster/poster13.webp",
    focus: "http://localhost:3000/focus/focus13.webp",
    title: "http://localhost:3000/title/title13.webp",
  },
  {
    id: 14,
    label: "Kung Fu Panda 3",
    wide: "http://localhost:3000/wide/wide14.webp",
    poster: "http://localhost:3000/poster/poster14.webp",
    focus: "http://localhost:3000/focus/focus14.webp",
    title: "http://localhost:3000/title/title14.webp",
  },
  {
    id: 15,
    label: "Dracula Untold",
    wide: "http://localhost:3000/wide/wide15.webp",
    poster: "http://localhost:3000/poster/poster15.webp",
    focus: "http://localhost:3000/focus/focus15.webp",
    title: "http://localhost:3000/title/title15.webp",
  },
  {
    id: 16,
    label: "Avatar: The Way of Water",
    wide: "http://localhost:3000/wide/wide16.webp",
    poster: "http://localhost:3000/poster/poster16.webp",
    focus: "http://localhost:3000/focus/focus16.webp",
    title: "http://localhost:3000/title/title16.webp",
  },
  {
    id: 17,
    label: "Godzilla Vs Kong",
    wide: "http://localhost:3000/wide/wide17.webp",
    poster: "http://localhost:3000/poster/poster17.webp",
    focus: "http://localhost:3000/focus/focus17.webp",
    title: "http://localhost:3000/title/title17.webp",
  },
];
export const recommendation_13 = [
  {
    id: 14,
    label: "Kung Fu Panda 3",
    wide: "http://localhost:3000/wide/wide14.webp",
    poster: "http://localhost:3000/poster/poster14.webp",
    focus: "http://localhost:3000/focus/focus14.webp",
    title: "http://localhost:3000/title/title14.webp",
  },
  {
    id: 15,
    label: "Dracula Untold",
    wide: "http://localhost:3000/wide/wide15.webp",
    poster: "http://localhost:3000/poster/poster15.webp",
    focus: "http://localhost:3000/focus/focus15.webp",
    title: "http://localhost:3000/title/title15.webp",
  },
  {
    id: 16,
    label: "Avatar: The Way of Water",
    wide: "http://localhost:3000/wide/wide16.webp",
    poster: "http://localhost:3000/poster/poster16.webp",
    focus: "http://localhost:3000/focus/focus16.webp",
    title: "http://localhost:3000/title/title16.webp",
  },
  {
    id: 17,
    label: "Godzilla Vs Kong",
    wide: "http://localhost:3000/wide/wide17.webp",
    poster: "http://localhost:3000/poster/poster17.webp",
    focus: "http://localhost:3000/focus/focus17.webp",
    title: "http://localhost:3000/title/title17.webp",
  },
  {
    id: 18,
    label: "Jurassic World: Fallen Kingdom",
    wide: "http://localhost:3000/wide/wide18.webp",
    poster: "http://localhost:3000/poster/poster18.webp",
    focus: "http://localhost:3000/focus/focus18.webp",
    title: "http://localhost:3000/title/title18.webp",
  },
];
export const recommendation_14 = [
  {
    id: 15,
    label: "Dracula Untold",
    wide: "http://localhost:3000/wide/wide15.webp",
    poster: "http://localhost:3000/poster/poster15.webp",
    focus: "http://localhost:3000/focus/focus15.webp",
    title: "http://localhost:3000/title/title15.webp",
  },
  {
    id: 16,
    label: "Avatar: The Way of Water",
    wide: "http://localhost:3000/wide/wide16.webp",
    poster: "http://localhost:3000/poster/poster16.webp",
    focus: "http://localhost:3000/focus/focus16.webp",
    title: "http://localhost:3000/title/title16.webp",
  },
  {
    id: 17,
    label: "Godzilla Vs Kong",
    wide: "http://localhost:3000/wide/wide17.webp",
    poster: "http://localhost:3000/poster/poster17.webp",
    focus: "http://localhost:3000/focus/focus17.webp",
    title: "http://localhost:3000/title/title17.webp",
  },
  {
    id: 18,
    label: "Jurassic World: Fallen Kingdom",
    wide: "http://localhost:3000/wide/wide18.webp",
    poster: "http://localhost:3000/poster/poster18.webp",
    focus: "http://localhost:3000/focus/focus18.webp",
    title: "http://localhost:3000/title/title18.webp",
  },
  {
    id: 19,
    label: "Alien: Convenant",
    wide: "http://localhost:3000/wide/wide19.webp",
    poster: "http://localhost:3000/poster/poster19.webp",
    focus: "http://localhost:3000/focus/focus19.webp",
    title: "http://localhost:3000/title/title19.webp",
  },
];
export const recommendation_15 = [
  {
    id: 16,
    label: "Avatar: The Way of Water",
    wide: "http://localhost:3000/wide/wide16.webp",
    poster: "http://localhost:3000/poster/poster16.webp",
    focus: "http://localhost:3000/focus/focus16.webp",
    title: "http://localhost:3000/title/title16.webp",
  },
  {
    id: 17,
    label: "Godzilla Vs Kong",
    wide: "http://localhost:3000/wide/wide17.webp",
    poster: "http://localhost:3000/poster/poster17.webp",
    focus: "http://localhost:3000/focus/focus17.webp",
    title: "http://localhost:3000/title/title17.webp",
  },
  {
    id: 18,
    label: "Jurassic World: Fallen Kingdom",
    wide: "http://localhost:3000/wide/wide18.webp",
    poster: "http://localhost:3000/poster/poster18.webp",
    focus: "http://localhost:3000/focus/focus18.webp",
    title: "http://localhost:3000/title/title18.webp",
  },
  {
    id: 19,
    label: "Alien: Convenant",
    wide: "http://localhost:3000/wide/wide19.webp",
    poster: "http://localhost:3000/poster/poster19.webp",
    focus: "http://localhost:3000/focus/focus19.webp",
    title: "http://localhost:3000/title/title19.webp",
  },
  {
    id: 20,
    label: "Godzilla",
    wide: "http://localhost:3000/wide/wide20.webp",
    poster: "http://localhost:3000/poster/poster20.webp",
    focus: "http://localhost:3000/focus/focus20.webp",
    title: "http://localhost:3000/title/title20.webp",
  },
];
export const recommendation_16 = [
  {
    id: 17,
    label: "Godzilla Vs Kong",
    wide: "http://localhost:3000/wide/wide17.webp",
    poster: "http://localhost:3000/poster/poster17.webp",
    focus: "http://localhost:3000/focus/focus17.webp",
    title: "http://localhost:3000/title/title17.webp",
  },
  {
    id: 18,
    label: "Jurassic World: Fallen Kingdom",
    wide: "http://localhost:3000/wide/wide18.webp",
    poster: "http://localhost:3000/poster/poster18.webp",
    focus: "http://localhost:3000/focus/focus18.webp",
    title: "http://localhost:3000/title/title18.webp",
  },
  {
    id: 19,
    label: "Alien: Convenant",
    wide: "http://localhost:3000/wide/wide19.webp",
    poster: "http://localhost:3000/poster/poster19.webp",
    focus: "http://localhost:3000/focus/focus19.webp",
    title: "http://localhost:3000/title/title19.webp",
  },
  {
    id: 20,
    label: "Godzilla",
    wide: "http://localhost:3000/wide/wide20.webp",
    poster: "http://localhost:3000/poster/poster20.webp",
    focus: "http://localhost:3000/focus/focus20.webp",
    title: "http://localhost:3000/title/title20.webp",
  },
  {
    id: 21,
    label: "The Batman",
    wide: "http://localhost:3000/wide/wide21.webp",
    poster: "http://localhost:3000/poster/poster21.webp",
    focus: "http://localhost:3000/focus/focus21.webp",
    title: "http://localhost:3000/title/title21.webp",
  },
];
export const recommendation_17 = [
  {
    id: 18,
    label: "Jurassic World: Fallen Kingdom",
    wide: "http://localhost:3000/wide/wide18.webp",
    poster: "http://localhost:3000/poster/poster18.webp",
    focus: "http://localhost:3000/focus/focus18.webp",
    title: "http://localhost:3000/title/title18.webp",
  },
  {
    id: 19,
    label: "Alien: Convenant",
    wide: "http://localhost:3000/wide/wide19.webp",
    poster: "http://localhost:3000/poster/poster19.webp",
    focus: "http://localhost:3000/focus/focus19.webp",
    title: "http://localhost:3000/title/title19.webp",
  },
  {
    id: 20,
    label: "Godzilla",
    wide: "http://localhost:3000/wide/wide20.webp",
    poster: "http://localhost:3000/poster/poster20.webp",
    focus: "http://localhost:3000/focus/focus20.webp",
    title: "http://localhost:3000/title/title20.webp",
  },
  {
    id: 21,
    label: "The Batman",
    wide: "http://localhost:3000/wide/wide21.webp",
    poster: "http://localhost:3000/poster/poster21.webp",
    focus: "http://localhost:3000/focus/focus21.webp",
    title: "http://localhost:3000/title/title21.webp",
  },
  {
    id: 22,
    label: "Justice League",
    wide: "http://localhost:3000/wide/wide22.webp",
    poster: "http://localhost:3000/poster/poster22.webp",
    focus: "http://localhost:3000/focus/focus22.webp",
    title: "http://localhost:3000/title/title22.webp",
  },
];
export const recommendation_18 = [
  {
    id: 19,
    label: "Alien: Convenant",
    wide: "http://localhost:3000/wide/wide19.webp",
    poster: "http://localhost:3000/poster/poster19.webp",
    focus: "http://localhost:3000/focus/focus19.webp",
    title: "http://localhost:3000/title/title19.webp",
  },
  {
    id: 20,
    label: "Godzilla",
    wide: "http://localhost:3000/wide/wide20.webp",
    poster: "http://localhost:3000/poster/poster20.webp",
    focus: "http://localhost:3000/focus/focus20.webp",
    title: "http://localhost:3000/title/title20.webp",
  },
  {
    id: 21,
    label: "The Batman",
    wide: "http://localhost:3000/wide/wide21.webp",
    poster: "http://localhost:3000/poster/poster21.webp",
    focus: "http://localhost:3000/focus/focus21.webp",
    title: "http://localhost:3000/title/title21.webp",
  },
  {
    id: 22,
    label: "Justice League",
    wide: "http://localhost:3000/wide/wide22.webp",
    poster: "http://localhost:3000/poster/poster22.webp",
    focus: "http://localhost:3000/focus/focus22.webp",
    title: "http://localhost:3000/title/title22.webp",
  },
  {
    id: 23,
    label: "Aquaman",
    wide: "http://localhost:3000/wide/wide23.webp",
    poster: "http://localhost:3000/poster/poster23.webp",
    focus: "http://localhost:3000/focus/focus23.webp",
    title: "http://localhost:3000/title/title23.webp",
  },
];
export const recommendation_19 = [
  {
    id: 20,
    label: "Godzilla",
    wide: "http://localhost:3000/wide/wide20.webp",
    poster: "http://localhost:3000/poster/poster20.webp",
    focus: "http://localhost:3000/focus/focus20.webp",
    title: "http://localhost:3000/title/title20.webp",
  },
  {
    id: 21,
    label: "The Batman",
    wide: "http://localhost:3000/wide/wide21.webp",
    poster: "http://localhost:3000/poster/poster21.webp",
    focus: "http://localhost:3000/focus/focus21.webp",
    title: "http://localhost:3000/title/title21.webp",
  },
  {
    id: 22,
    label: "Justice League",
    wide: "http://localhost:3000/wide/wide22.webp",
    poster: "http://localhost:3000/poster/poster22.webp",
    focus: "http://localhost:3000/focus/focus22.webp",
    title: "http://localhost:3000/title/title22.webp",
  },
  {
    id: 23,
    label: "Aquaman",
    wide: "http://localhost:3000/wide/wide23.webp",
    poster: "http://localhost:3000/poster/poster23.webp",
    focus: "http://localhost:3000/focus/focus23.webp",
    title: "http://localhost:3000/title/title23.webp",
  },
  {
    id: 24,
    label: "Thor: Ragnarok",
    wide: "http://localhost:3000/wide/wide24.webp",
    poster: "http://localhost:3000/poster/poster24.webp",
    focus: "http://localhost:3000/focus/focus24.webp",
    title: "http://localhost:3000/title/title24.webp",
  },
];
export const recommendation_20 = [
  {
    id: 21,
    label: "The Batman",
    wide: "http://localhost:3000/wide/wide21.webp",
    poster: "http://localhost:3000/poster/poster21.webp",
    focus: "http://localhost:3000/focus/focus21.webp",
    title: "http://localhost:3000/title/title21.webp",
  },
  {
    id: 22,
    label: "Justice League",
    wide: "http://localhost:3000/wide/wide22.webp",
    poster: "http://localhost:3000/poster/poster22.webp",
    focus: "http://localhost:3000/focus/focus22.webp",
    title: "http://localhost:3000/title/title22.webp",
  },
  {
    id: 23,
    label: "Aquaman",
    wide: "http://localhost:3000/wide/wide23.webp",
    poster: "http://localhost:3000/poster/poster23.webp",
    focus: "http://localhost:3000/focus/focus23.webp",
    title: "http://localhost:3000/title/title23.webp",
  },
  {
    id: 24,
    label: "Thor: Ragnarok",
    wide: "http://localhost:3000/wide/wide24.webp",
    poster: "http://localhost:3000/poster/poster24.webp",
    focus: "http://localhost:3000/focus/focus24.webp",
    title: "http://localhost:3000/title/title24.webp",
  },
  {
    id: 25,
    label: "The Jungle Book",
    wide: "http://localhost:3000/wide/wide25.webp",
    poster: "http://localhost:3000/poster/poster25.webp",
    focus: "http://localhost:3000/focus/focus25.webp",
    title: "http://localhost:3000/title/title25.webp",
  },
];
export const recommendation_21 = [
  {
    id: 22,
    label: "Justice League",
    wide: "http://localhost:3000/wide/wide22.webp",
    poster: "http://localhost:3000/poster/poster22.webp",
    focus: "http://localhost:3000/focus/focus22.webp",
    title: "http://localhost:3000/title/title22.webp",
  },
  {
    id: 23,
    label: "Aquaman",
    wide: "http://localhost:3000/wide/wide23.webp",
    poster: "http://localhost:3000/poster/poster23.webp",
    focus: "http://localhost:3000/focus/focus23.webp",
    title: "http://localhost:3000/title/title23.webp",
  },
  {
    id: 24,
    label: "Thor: Ragnarok",
    wide: "http://localhost:3000/wide/wide24.webp",
    poster: "http://localhost:3000/poster/poster24.webp",
    focus: "http://localhost:3000/focus/focus24.webp",
    title: "http://localhost:3000/title/title24.webp",
  },
  {
    id: 25,
    label: "The Jungle Book",
    wide: "http://localhost:3000/wide/wide25.webp",
    poster: "http://localhost:3000/poster/poster25.webp",
    focus: "http://localhost:3000/focus/focus25.webp",
    title: "http://localhost:3000/title/title25.webp",
  },
  {
    id: 26,
    label: "Spider Man: Into The Spider Verse",
    wide: "http://localhost:3000/wide/wide26.webp",
    poster: "http://localhost:3000/poster/poster26.webp",
    focus: "http://localhost:3000/focus/focus26.webp",
    title: "http://localhost:3000/title/title26.webp",
  },
];
export const recommendation_22 = [
  {
    id: 23,
    label: "Aquaman",
    wide: "http://localhost:3000/wide/wide23.webp",
    poster: "http://localhost:3000/poster/poster23.webp",
    focus: "http://localhost:3000/focus/focus23.webp",
    title: "http://localhost:3000/title/title23.webp",
  },
  {
    id: 24,
    label: "Thor: Ragnarok",
    wide: "http://localhost:3000/wide/wide24.webp",
    poster: "http://localhost:3000/poster/poster24.webp",
    focus: "http://localhost:3000/focus/focus24.webp",
    title: "http://localhost:3000/title/title24.webp",
  },
  {
    id: 25,
    label: "The Jungle Book",
    wide: "http://localhost:3000/wide/wide25.webp",
    poster: "http://localhost:3000/poster/poster25.webp",
    focus: "http://localhost:3000/focus/focus25.webp",
    title: "http://localhost:3000/title/title25.webp",
  },
  {
    id: 26,
    label: "Spider Man: Into The Spider Verse",
    wide: "http://localhost:3000/wide/wide26.webp",
    poster: "http://localhost:3000/poster/poster26.webp",
    focus: "http://localhost:3000/focus/focus26.webp",
    title: "http://localhost:3000/title/title26.webp",
  },
  {
    id: 27,
    label: "Moana",
    wide: "http://localhost:3000/wide/wide27.webp",
    poster: "http://localhost:3000/poster/poster27.webp",
    focus: "http://localhost:3000/focus/focus27.webp",
    title: "http://localhost:3000/title/title27.webp",
  },
];
export const recommendation_23 = [
  {
    id: 24,
    label: "Thor: Ragnarok",
    wide: "http://localhost:3000/wide/wide24.webp",
    poster: "http://localhost:3000/poster/poster24.webp",
    focus: "http://localhost:3000/focus/focus24.webp",
    title: "http://localhost:3000/title/title24.webp",
  },
  {
    id: 25,
    label: "The Jungle Book",
    wide: "http://localhost:3000/wide/wide25.webp",
    poster: "http://localhost:3000/poster/poster25.webp",
    focus: "http://localhost:3000/focus/focus25.webp",
    title: "http://localhost:3000/title/title25.webp",
  },
  {
    id: 26,
    label: "Spider Man: Into The Spider Verse",
    wide: "http://localhost:3000/wide/wide26.webp",
    poster: "http://localhost:3000/poster/poster26.webp",
    focus: "http://localhost:3000/focus/focus26.webp",
    title: "http://localhost:3000/title/title26.webp",
  },
  {
    id: 27,
    label: "Moana",
    wide: "http://localhost:3000/wide/wide27.webp",
    poster: "http://localhost:3000/poster/poster27.webp",
    focus: "http://localhost:3000/focus/focus27.webp",
    title: "http://localhost:3000/title/title27.webp",
  },
  {
    id: 28,
    label: "Guardian Of The Galaxy",
    wide: "http://localhost:3000/wide/wide28.webp",
    poster: "http://localhost:3000/poster/poster28.webp",
    focus: "http://localhost:3000/focus/focus28.webp",
    title: "http://localhost:3000/title/title28.webp",
  },
];
export const recommendation_24 = [
  {
    id: 25,
    label: "The Jungle Book",
    wide: "http://localhost:3000/wide/wide25.webp",
    poster: "http://localhost:3000/poster/poster25.webp",
    focus: "http://localhost:3000/focus/focus25.webp",
    title: "http://localhost:3000/title/title25.webp",
  },
  {
    id: 26,
    label: "Spider Man: Into The Spider Verse",
    wide: "http://localhost:3000/wide/wide26.webp",
    poster: "http://localhost:3000/poster/poster26.webp",
    focus: "http://localhost:3000/focus/focus26.webp",
    title: "http://localhost:3000/title/title26.webp",
  },
  {
    id: 27,
    label: "Moana",
    wide: "http://localhost:3000/wide/wide27.webp",
    poster: "http://localhost:3000/poster/poster27.webp",
    focus: "http://localhost:3000/focus/focus27.webp",
    title: "http://localhost:3000/title/title27.webp",
  },
  {
    id: 28,
    label: "Guardian Of The Galaxy",
    wide: "http://localhost:3000/wide/wide28.webp",
    poster: "http://localhost:3000/poster/poster28.webp",
    focus: "http://localhost:3000/focus/focus28.webp",
    title: "http://localhost:3000/title/title28.webp",
  },
  {
    id: 29,
    label: "Dragon",
    wide: "http://localhost:3000/wide/wide29.webp",
    poster: "http://localhost:3000/poster/poster29.webp",
    focus: "http://localhost:3000/focus/focus29.webp",
    title: "http://localhost:3000/title/title29.webp",
  },
];
export const recommendation_25 = [
  {
    id: 26,
    label: "Spider Man: Into The Spider Verse",
    wide: "http://localhost:3000/wide/wide26.webp",
    poster: "http://localhost:3000/poster/poster26.webp",
    focus: "http://localhost:3000/focus/focus26.webp",
    title: "http://localhost:3000/title/title26.webp",
  },
  {
    id: 27,
    label: "Moana",
    wide: "http://localhost:3000/wide/wide27.webp",
    poster: "http://localhost:3000/poster/poster27.webp",
    focus: "http://localhost:3000/focus/focus27.webp",
    title: "http://localhost:3000/title/title27.webp",
  },
  {
    id: 28,
    label: "Guardian Of The Galaxy",
    wide: "http://localhost:3000/wide/wide28.webp",
    poster: "http://localhost:3000/poster/poster28.webp",
    focus: "http://localhost:3000/focus/focus28.webp",
    title: "http://localhost:3000/title/title28.webp",
  },
  {
    id: 29,
    label: "Dragon",
    wide: "http://localhost:3000/wide/wide29.webp",
    poster: "http://localhost:3000/poster/poster29.webp",
    focus: "http://localhost:3000/focus/focus29.webp",
    title: "http://localhost:3000/title/title29.webp",
  },
  {
    id: 30,
    label: "Alita: Battle Angel",
    wide: "http://localhost:3000/wide/wide30.webp",
    poster: "http://localhost:3000/poster/poster30.webp",
    focus: "http://localhost:3000/focus/focus30.webp",
    title: "http://localhost:3000/title/title30.webp",
  },
];
export const recommendation_26 = [
  {
    id: 27,
    label: "Moana",
    wide: "http://localhost:3000/wide/wide27.webp",
    poster: "http://localhost:3000/poster/poster27.webp",
    focus: "http://localhost:3000/focus/focus27.webp",
    title: "http://localhost:3000/title/title27.webp",
  },
  {
    id: 28,
    label: "Guardian Of The Galaxy",
    wide: "http://localhost:3000/wide/wide28.webp",
    poster: "http://localhost:3000/poster/poster28.webp",
    focus: "http://localhost:3000/focus/focus28.webp",
    title: "http://localhost:3000/title/title28.webp",
  },
  {
    id: 29,
    label: "Dragon",
    wide: "http://localhost:3000/wide/wide29.webp",
    poster: "http://localhost:3000/poster/poster29.webp",
    focus: "http://localhost:3000/focus/focus29.webp",
    title: "http://localhost:3000/title/title29.webp",
  },
  {
    id: 30,
    label: "Alita: Battle Angel",
    wide: "http://localhost:3000/wide/wide30.webp",
    poster: "http://localhost:3000/poster/poster30.webp",
    focus: "http://localhost:3000/focus/focus30.webp",
    title: "http://localhost:3000/title/title30.webp",
  },
  {
    id: 31,
    label: "Dune",
    wide: "http://localhost:3000/wide/wide31.webp",
    poster: "http://localhost:3000/poster/poster31.webp",
    focus: "http://localhost:3000/focus/focus31.webp",
    title: "http://localhost:3000/title/title31.webp",
  },
];
export const recommendation_27 = [
  {
    id: 28,
    label: "Guardian Of The Galaxy",
    wide: "http://localhost:3000/wide/wide28.webp",
    poster: "http://localhost:3000/poster/poster28.webp",
    focus: "http://localhost:3000/focus/focus28.webp",
    title: "http://localhost:3000/title/title28.webp",
  },
  {
    id: 29,
    label: "Dragon",
    wide: "http://localhost:3000/wide/wide29.webp",
    poster: "http://localhost:3000/poster/poster29.webp",
    focus: "http://localhost:3000/focus/focus29.webp",
    title: "http://localhost:3000/title/title29.webp",
  },
  {
    id: 30,
    label: "Alita: Battle Angel",
    wide: "http://localhost:3000/wide/wide30.webp",
    poster: "http://localhost:3000/poster/poster30.webp",
    focus: "http://localhost:3000/focus/focus30.webp",
    title: "http://localhost:3000/title/title30.webp",
  },
  {
    id: 31,
    label: "Dune",
    wide: "http://localhost:3000/wide/wide31.webp",
    poster: "http://localhost:3000/poster/poster31.webp",
    focus: "http://localhost:3000/focus/focus31.webp",
    title: "http://localhost:3000/title/title31.webp",
  },
  {
    id: 32,
    label: "Extraction",
    wide: "http://localhost:3000/wide/wide32.webp",
    poster: "http://localhost:3000/poster/poster32.webp",
    focus: "http://localhost:3000/focus/focus32.webp",
    title: "http://localhost:3000/title/title32.webp",
  },
];
export const recommendation_28 = [
  {
    id: 29,
    label: "Dragon",
    wide: "http://localhost:3000/wide/wide29.webp",
    poster: "http://localhost:3000/poster/poster29.webp",
    focus: "http://localhost:3000/focus/focus29.webp",
    title: "http://localhost:3000/title/title29.webp",
  },
  {
    id: 30,
    label: "Alita: Battle Angel",
    wide: "http://localhost:3000/wide/wide30.webp",
    poster: "http://localhost:3000/poster/poster30.webp",
    focus: "http://localhost:3000/focus/focus30.webp",
    title: "http://localhost:3000/title/title30.webp",
  },
  {
    id: 31,
    label: "Dune",
    wide: "http://localhost:3000/wide/wide31.webp",
    poster: "http://localhost:3000/poster/poster31.webp",
    focus: "http://localhost:3000/focus/focus31.webp",
    title: "http://localhost:3000/title/title31.webp",
  },
  {
    id: 32,
    label: "Extraction",
    wide: "http://localhost:3000/wide/wide32.webp",
    poster: "http://localhost:3000/poster/poster32.webp",
    focus: "http://localhost:3000/focus/focus32.webp",
    title: "http://localhost:3000/title/title32.webp",
  },
  {
    id: 33,
    label: "Pirates of the Caribbean: Dead Men Tell No Tales",
    wide: "http://localhost:3000/wide/wide33.webp",
    poster: "http://localhost:3000/poster/poster33.webp",
    focus: "http://localhost:3000/focus/focus33.webp",
    title: "http://localhost:3000/title/title33.webp",
  },
];
export const recommendation_29 = [
  {
    id: 30,
    label: "Alita: Battle Angel",
    wide: "http://localhost:3000/wide/wide30.webp",
    poster: "http://localhost:3000/poster/poster30.webp",
    focus: "http://localhost:3000/focus/focus30.webp",
    title: "http://localhost:3000/title/title30.webp",
  },
  {
    id: 31,
    label: "Dune",
    wide: "http://localhost:3000/wide/wide31.webp",
    poster: "http://localhost:3000/poster/poster31.webp",
    focus: "http://localhost:3000/focus/focus31.webp",
    title: "http://localhost:3000/title/title31.webp",
  },
  {
    id: 32,
    label: "Extraction",
    wide: "http://localhost:3000/wide/wide32.webp",
    poster: "http://localhost:3000/poster/poster32.webp",
    focus: "http://localhost:3000/focus/focus32.webp",
    title: "http://localhost:3000/title/title32.webp",
  },
  {
    id: 33,
    label: "Pirates of the Caribbean: Dead Men Tell No Tales",
    wide: "http://localhost:3000/wide/wide33.webp",
    poster: "http://localhost:3000/poster/poster33.webp",
    focus: "http://localhost:3000/focus/focus33.webp",
    title: "http://localhost:3000/title/title33.webp",
  },
  {
    id: 34,
    label: "Call of Duty: Modern Warfare",
    wide: "http://localhost:3000/wide/wide34.webp",
    poster: "http://localhost:3000/poster/poster34.webp",
    focus: "http://localhost:3000/focus/focus34.webp",
    title: "http://localhost:3000/title/title34.webp",
  },
];
export const recommendation_30 = [
  {
    id: 31,
    label: "Dune",
    wide: "http://localhost:3000/wide/wide31.webp",
    poster: "http://localhost:3000/poster/poster31.webp",
    focus: "http://localhost:3000/focus/focus31.webp",
    title: "http://localhost:3000/title/title31.webp",
  },
  {
    id: 32,
    label: "Extraction",
    wide: "http://localhost:3000/wide/wide32.webp",
    poster: "http://localhost:3000/poster/poster32.webp",
    focus: "http://localhost:3000/focus/focus32.webp",
    title: "http://localhost:3000/title/title32.webp",
  },
  {
    id: 33,
    label: "Pirates of the Caribbean: Dead Men Tell No Tales",
    wide: "http://localhost:3000/wide/wide33.webp",
    poster: "http://localhost:3000/poster/poster33.webp",
    focus: "http://localhost:3000/focus/focus33.webp",
    title: "http://localhost:3000/title/title33.webp",
  },
  {
    id: 34,
    label: "Call of Duty: Modern Warfare",
    wide: "http://localhost:3000/wide/wide34.webp",
    poster: "http://localhost:3000/poster/poster34.webp",
    focus: "http://localhost:3000/focus/focus34.webp",
    title: "http://localhost:3000/title/title34.webp",
  },
  {
    id: 35,
    label: "Halloween Ends",
    wide: "http://localhost:3000/wide/wide35.webp",
    poster: "http://localhost:3000/poster/poster35.webp",
    focus: "http://localhost:3000/focus/focus35.webp",
    title: "http://localhost:3000/title/title35.webp",
  },
];
export const recommendation_31 = [
  {
    id: 32,
    label: "Extraction",
    wide: "http://localhost:3000/wide/wide32.webp",
    poster: "http://localhost:3000/poster/poster32.webp",
    focus: "http://localhost:3000/focus/focus32.webp",
    title: "http://localhost:3000/title/title32.webp",
  },
  {
    id: 33,
    label: "Pirates of the Caribbean: Dead Men Tell No Tales",
    wide: "http://localhost:3000/wide/wide33.webp",
    poster: "http://localhost:3000/poster/poster33.webp",
    focus: "http://localhost:3000/focus/focus33.webp",
    title: "http://localhost:3000/title/title33.webp",
  },
  {
    id: 34,
    label: "Call of Duty: Modern Warfare",
    wide: "http://localhost:3000/wide/wide34.webp",
    poster: "http://localhost:3000/poster/poster34.webp",
    focus: "http://localhost:3000/focus/focus34.webp",
    title: "http://localhost:3000/title/title34.webp",
  },
  {
    id: 35,
    label: "Halloween Ends",
    wide: "http://localhost:3000/wide/wide35.webp",
    poster: "http://localhost:3000/poster/poster35.webp",
    focus: "http://localhost:3000/focus/focus35.webp",
    title: "http://localhost:3000/title/title35.webp",
  },
  {
    id: 36,
    label: "Uncharted",
    wide: "http://localhost:3000/wide/wide36.webp",
    poster: "http://localhost:3000/poster/poster36.webp",
    focus: "http://localhost:3000/focus/focus36.webp",
    title: "http://localhost:3000/title/title36.webp",
  },
];
export const recommendation_32 = [
  {
    id: 33,
    label: "Pirates of the Caribbean: Dead Men Tell No Tales",
    wide: "http://localhost:3000/wide/wide33.webp",
    poster: "http://localhost:3000/poster/poster33.webp",
    focus: "http://localhost:3000/focus/focus33.webp",
    title: "http://localhost:3000/title/title33.webp",
  },
  {
    id: 34,
    label: "Call of Duty: Modern Warfare",
    wide: "http://localhost:3000/wide/wide34.webp",
    poster: "http://localhost:3000/poster/poster34.webp",
    focus: "http://localhost:3000/focus/focus34.webp",
    title: "http://localhost:3000/title/title34.webp",
  },
  {
    id: 35,
    label: "Halloween Ends",
    wide: "http://localhost:3000/wide/wide35.webp",
    poster: "http://localhost:3000/poster/poster35.webp",
    focus: "http://localhost:3000/focus/focus35.webp",
    title: "http://localhost:3000/title/title35.webp",
  },
  {
    id: 36,
    label: "Uncharted",
    wide: "http://localhost:3000/wide/wide36.webp",
    poster: "http://localhost:3000/poster/poster36.webp",
    focus: "http://localhost:3000/focus/focus36.webp",
    title: "http://localhost:3000/title/title36.webp",
  },
  {
    id: 37,
    label: "The Northman",
    wide: "http://localhost:3000/wide/wide37.webp",
    poster: "http://localhost:3000/poster/poster37.webp",
    focus: "http://localhost:3000/focus/focus37.webp",
    title: "http://localhost:3000/title/title37.webp",
  },
];
export const recommendation_33 = [
  {
    id: 34,
    label: "Call of Duty: Modern Warfare",
    wide: "http://localhost:3000/wide/wide34.webp",
    poster: "http://localhost:3000/poster/poster34.webp",
    focus: "http://localhost:3000/focus/focus34.webp",
    title: "http://localhost:3000/title/title34.webp",
  },
  {
    id: 35,
    label: "Halloween Ends",
    wide: "http://localhost:3000/wide/wide35.webp",
    poster: "http://localhost:3000/poster/poster35.webp",
    focus: "http://localhost:3000/focus/focus35.webp",
    title: "http://localhost:3000/title/title35.webp",
  },
  {
    id: 36,
    label: "Uncharted",
    wide: "http://localhost:3000/wide/wide36.webp",
    poster: "http://localhost:3000/poster/poster36.webp",
    focus: "http://localhost:3000/focus/focus36.webp",
    title: "http://localhost:3000/title/title36.webp",
  },
  {
    id: 37,
    label: "The Northman",
    wide: "http://localhost:3000/wide/wide37.webp",
    poster: "http://localhost:3000/poster/poster37.webp",
    focus: "http://localhost:3000/focus/focus37.webp",
    title: "http://localhost:3000/title/title37.webp",
  },
  {
    id: 38,
    label: "John Wick Parabellum",
    wide: "http://localhost:3000/wide/wide38.webp",
    poster: "http://localhost:3000/poster/poster38.webp",
    focus: "http://localhost:3000/focus/focus38.webp",
    title: "http://localhost:3000/title/title38.webp",
  },
];
export const recommendation_34 = [
  {
    id: 35,
    label: "Halloween Ends",
    wide: "http://localhost:3000/wide/wide35.webp",
    poster: "http://localhost:3000/poster/poster35.webp",
    focus: "http://localhost:3000/focus/focus35.webp",
    title: "http://localhost:3000/title/title35.webp",
  },
  {
    id: 36,
    label: "Uncharted",
    wide: "http://localhost:3000/wide/wide36.webp",
    poster: "http://localhost:3000/poster/poster36.webp",
    focus: "http://localhost:3000/focus/focus36.webp",
    title: "http://localhost:3000/title/title36.webp",
  },
  {
    id: 37,
    label: "The Northman",
    wide: "http://localhost:3000/wide/wide37.webp",
    poster: "http://localhost:3000/poster/poster37.webp",
    focus: "http://localhost:3000/focus/focus37.webp",
    title: "http://localhost:3000/title/title37.webp",
  },
  {
    id: 38,
    label: "John Wick Parabellum",
    wide: "http://localhost:3000/wide/wide38.webp",
    poster: "http://localhost:3000/poster/poster38.webp",
    focus: "http://localhost:3000/focus/focus38.webp",
    title: "http://localhost:3000/title/title38.webp",
  },
  {
    id: 39,
    label: "Morbius",
    wide: "http://localhost:3000/wide/wide39.webp",
    poster: "http://localhost:3000/poster/poster39.webp",
    focus: "http://localhost:3000/focus/focus39.webp",
    title: "http://localhost:3000/title/title39.webp",
  },
];
export const recommendation_35 = [
  {
    id: 36,
    label: "Uncharted",
    wide: "http://localhost:3000/wide/wide36.webp",
    poster: "http://localhost:3000/poster/poster36.webp",
    focus: "http://localhost:3000/focus/focus36.webp",
    title: "http://localhost:3000/title/title36.webp",
  },
  {
    id: 37,
    label: "The Northman",
    wide: "http://localhost:3000/wide/wide37.webp",
    poster: "http://localhost:3000/poster/poster37.webp",
    focus: "http://localhost:3000/focus/focus37.webp",
    title: "http://localhost:3000/title/title37.webp",
  },
  {
    id: 38,
    label: "John Wick Parabellum",
    wide: "http://localhost:3000/wide/wide38.webp",
    poster: "http://localhost:3000/poster/poster38.webp",
    focus: "http://localhost:3000/focus/focus38.webp",
    title: "http://localhost:3000/title/title38.webp",
  },
  {
    id: 39,
    label: "Morbius",
    wide: "http://localhost:3000/wide/wide39.webp",
    poster: "http://localhost:3000/poster/poster39.webp",
    focus: "http://localhost:3000/focus/focus39.webp",
    title: "http://localhost:3000/title/title39.webp",
  },
  {
    id: 40,
    label: "Jungle Cruise",
    wide: "http://localhost:3000/wide/wide40.webp",
    poster: "http://localhost:3000/poster/poster40.webp",
    focus: "http://localhost:3000/focus/focus40.webp",
    title: "http://localhost:3000/title/title40.webp",
  },
];
export const recommendation_36 = [
  {
    id: 37,
    label: "The Northman",
    wide: "http://localhost:3000/wide/wide37.webp",
    poster: "http://localhost:3000/poster/poster37.webp",
    focus: "http://localhost:3000/focus/focus37.webp",
    title: "http://localhost:3000/title/title37.webp",
  },
  {
    id: 38,
    label: "John Wick Parabellum",
    wide: "http://localhost:3000/wide/wide38.webp",
    poster: "http://localhost:3000/poster/poster38.webp",
    focus: "http://localhost:3000/focus/focus38.webp",
    title: "http://localhost:3000/title/title38.webp",
  },
  {
    id: 39,
    label: "Morbius",
    wide: "http://localhost:3000/wide/wide39.webp",
    poster: "http://localhost:3000/poster/poster39.webp",
    focus: "http://localhost:3000/focus/focus39.webp",
    title: "http://localhost:3000/title/title39.webp",
  },
  {
    id: 40,
    label: "Jungle Cruise",
    wide: "http://localhost:3000/wide/wide40.webp",
    poster: "http://localhost:3000/poster/poster40.webp",
    focus: "http://localhost:3000/focus/focus40.webp",
    title: "http://localhost:3000/title/title40.webp",
  },
  {
    id: 1,
    label: "Doctor Strange in the Multiverse of Madness",
    wide: "http://localhost:3000/wide/wide1.webp",
    poster: "http://localhost:3000/poster/poster1.webp",
    focus: "http://localhost:3000/focus/focus1.webp",
    title: "http://localhost:3000/title/title1.webp",
    recommendations: [],
  },
];
export const recommendation_37 = [
  {
    id: 38,
    label: "John Wick Parabellum",
    wide: "http://localhost:3000/wide/wide38.webp",
    poster: "http://localhost:3000/poster/poster38.webp",
    focus: "http://localhost:3000/focus/focus38.webp",
    title: "http://localhost:3000/title/title38.webp",
  },
  {
    id: 39,
    label: "Morbius",
    wide: "http://localhost:3000/wide/wide39.webp",
    poster: "http://localhost:3000/poster/poster39.webp",
    focus: "http://localhost:3000/focus/focus39.webp",
    title: "http://localhost:3000/title/title39.webp",
  },
  {
    id: 40,
    label: "Jungle Cruise",
    wide: "http://localhost:3000/wide/wide40.webp",
    poster: "http://localhost:3000/poster/poster40.webp",
    focus: "http://localhost:3000/focus/focus40.webp",
    title: "http://localhost:3000/title/title40.webp",
  },
  {
    id: 1,
    label: "Doctor Strange in the Multiverse of Madness",
    wide: "http://localhost:3000/wide/wide1.webp",
    poster: "http://localhost:3000/poster/poster1.webp",
    focus: "http://localhost:3000/focus/focus1.webp",
    title: "http://localhost:3000/title/title1.webp",
    recommendations: [],
  },
  {
    id: 2,
    label: "Avengers: Endgame",
    wide: "http://localhost:3000/wide/wide2.webp",
    poster: "http://localhost:3000/poster/poster2.webp",
    focus: "http://localhost:3000/focus/focus2.webp",
    title: "http://localhost:3000/title/title2.webp",
  },
];
export const recommendation_38 = [
  {
    id: 39,
    label: "Morbius",
    wide: "http://localhost:3000/wide/wide39.webp",
    poster: "http://localhost:3000/poster/poster39.webp",
    focus: "http://localhost:3000/focus/focus39.webp",
    title: "http://localhost:3000/title/title39.webp",
  },
  {
    id: 40,
    label: "Jungle Cruise",
    wide: "http://localhost:3000/wide/wide40.webp",
    poster: "http://localhost:3000/poster/poster40.webp",
    focus: "http://localhost:3000/focus/focus40.webp",
    title: "http://localhost:3000/title/title40.webp",
  },
  {
    id: 1,
    label: "Doctor Strange in the Multiverse of Madness",
    wide: "http://localhost:3000/wide/wide1.webp",
    poster: "http://localhost:3000/poster/poster1.webp",
    focus: "http://localhost:3000/focus/focus1.webp",
    title: "http://localhost:3000/title/title1.webp",
    recommendations: [],
  },
  {
    id: 2,
    label: "Avengers: Endgame",
    wide: "http://localhost:3000/wide/wide2.webp",
    poster: "http://localhost:3000/poster/poster2.webp",
    focus: "http://localhost:3000/focus/focus2.webp",
    title: "http://localhost:3000/title/title2.webp",
  },
  {
    id: 3,
    label: "Avengers: Infinity War",
    wide: "http://localhost:3000/wide/wide3.webp",
    poster: "http://localhost:3000/poster/poster3.webp",
    focus: "http://localhost:3000/focus/focus3.webp",
    title: "http://localhost:3000/title/title3.webp",
  },
];
export const recommendation_39 = [
  {
    id: 40,
    label: "Jungle Cruise",
    wide: "http://localhost:3000/wide/wide40.webp",
    poster: "http://localhost:3000/poster/poster40.webp",
    focus: "http://localhost:3000/focus/focus40.webp",
    title: "http://localhost:3000/title/title40.webp",
  },
  {
    id: 1,
    label: "Doctor Strange in the Multiverse of Madness",
    wide: "http://localhost:3000/wide/wide1.webp",
    poster: "http://localhost:3000/poster/poster1.webp",
    focus: "http://localhost:3000/focus/focus1.webp",
    title: "http://localhost:3000/title/title1.webp",
    recommendations: [],
  },
  {
    id: 2,
    label: "Avengers: Endgame",
    wide: "http://localhost:3000/wide/wide2.webp",
    poster: "http://localhost:3000/poster/poster2.webp",
    focus: "http://localhost:3000/focus/focus2.webp",
    title: "http://localhost:3000/title/title2.webp",
  },
  {
    id: 3,
    label: "Avengers: Infinity War",
    wide: "http://localhost:3000/wide/wide3.webp",
    poster: "http://localhost:3000/poster/poster3.webp",
    focus: "http://localhost:3000/focus/focus3.webp",
    title: "http://localhost:3000/title/title3.webp",
  },
  {
    id: 4,
    label: "Venom",
    wide: "http://localhost:3000/wide/wide4.webp",
    poster: "http://localhost:3000/poster/poster4.webp",
    focus: "http://localhost:3000/focus/focus4.webp",
    title: "http://localhost:3000/title/title4.webp",
  },
];
export const recommendation_40 = [
  {
    id: 1,
    label: "Doctor Strange in the Multiverse of Madness",
    wide: "http://localhost:3000/wide/wide1.webp",
    poster: "http://localhost:3000/poster/poster1.webp",
    focus: "http://localhost:3000/focus/focus1.webp",
    title: "http://localhost:3000/title/title1.webp",
    recommendations: [],
  },
  {
    id: 2,
    label: "Avengers: Endgame",
    wide: "http://localhost:3000/wide/wide2.webp",
    poster: "http://localhost:3000/poster/poster2.webp",
    focus: "http://localhost:3000/focus/focus2.webp",
    title: "http://localhost:3000/title/title2.webp",
  },
  {
    id: 3,
    label: "Avengers: Infinity War",
    wide: "http://localhost:3000/wide/wide3.webp",
    poster: "http://localhost:3000/poster/poster3.webp",
    focus: "http://localhost:3000/focus/focus3.webp",
    title: "http://localhost:3000/title/title3.webp",
  },
  {
    id: 4,
    label: "Venom",
    wide: "http://localhost:3000/wide/wide4.webp",
    poster: "http://localhost:3000/poster/poster4.webp",
    focus: "http://localhost:3000/focus/focus4.webp",
    title: "http://localhost:3000/title/title4.webp",
  },
  {
    id: 5,
    label: "Transformers: The Last Knight",
    wide: "http://localhost:3000/wide/wide5.webp",
    poster: "http://localhost:3000/poster/poster5.webp",
    focus: "http://localhost:3000/focus/focus5.webp",
    title: "http://localhost:3000/title/title5.webp",
  },
];
